name: build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.11
      uses: actions/setup-node@v1
      with:
        node-version: '18.11'
    - name: Install yarn
      run: |
        yarn
      env:
        CI: true
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag komrade007/projetthematique:latest
      
    - name: Docker Push
      run: docker push komrade007/projetthematique
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      with:
        host: ${{ secrets.HOST_PRE }}
        username: ${{ secrets.USERNAME_SRV }}
        password: ${{ secrets.PASSWORD_SRV }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker pull komrade007/projetthematique:latest
          docker run -dit -p 80:80 komrade007/projetthematique:latest
